import SkiaBreathe from "./skia/Breathe";
import Ionicons from "@expo/vector-icons/Ionicons";
import { NavigationContainer, RouteProp } from "@react-navigation/native";
import { BottomTabNavigationOptions, createBottomTabNavigator } from "@react-navigation/bottom-tabs";

type Tabs = { Reanimated: undefined; Skia: undefined };

const { Navigator, Screen } = createBottomTabNavigator<Tabs>();

const reanimatedOptions = (props: { route: RouteProp<Tabs, "Reanimated">; navigation: any }): BottomTabNavigationOptions => {
  return {
    tabBarIcon: ({ color, size }) => {
      return <Ionicons name="chevron-back-sharp" color={color} size={size} />;
    },
  };
};

const skiaOptions = (props: { route: RouteProp<Tabs, "Skia">; navigation: any }): BottomTabNavigationOptions => {
  return {
    tabBarIcon: ({ color, size }) => {
      return <Ionicons name="chevron-forward-sharp" color={color} size={size} />;
    },
  };
};

export default function App() {

  const ws = new WebSocket('ws://0af3-171-67-254-10.ngrok.io'); // generated by ngrok so need to replace everytime
  ws.onopen = () => {
    console.log("connected");
    ws.send('something'); // send a message
  }
  ws.onmessage = (e) => {
    // a message was received
    console.log(e.data);
  };

  ws.onerror = (e) => {
    // an error occurred
    console.log(e);
  };

  ws.onclose = (e) => {
    // connection closed
    console.log(e.code, e.reason);
  };

  return (
    <NavigationContainer>
      <Navigator
        sceneContainerStyle={{ backgroundColor: "black" }}
        screenOptions={{
          tabBarShowLabel: false,
          headerTintColor: "#59ADA1",
          headerStyle: { backgroundColor: "#111" },
          headerShadowVisible: false,
          tabBarActiveTintColor: "#59ADA1",
          tabBarActiveBackgroundColor: "#000",
          tabBarInactiveBackgroundColor: "#000",
          tabBarStyle: { borderTopColor: "#222", borderTopWidth: 1 },
        }}
      >
        <Screen name="Skia" component={SkiaBreathe} options={skiaOptions} />
      </Navigator>
    </NavigationContainer>
  );
}
